name: Testing Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |-
          pip install .

      - name: Run Tests
        run: |-
          pytest -v IssModelTest/*.py -v

      - name: Check test status
        run: |-
          # Check the status of the most recent commit
          COMMIT_SHA=$(git rev-parse HEAD)
          TEST_STATUS=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY/commits/$COMMIT_SHA/status | jq -r '.state')
          
          # If the test status is failure, revert the commit
          if [ "$TEST_STATUS" = "failure" ]; then
            git revert --no-edit $COMMIT_SHA
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
